### ISSUE TITLE
Website and userscript not working

### ISSUE THREAD

**Issue by bbtora** [qsniyg/maxurl#7]
I tried the website today (few minutes ago) and it doesn't seem to be working for me. It's working on the mobile btw.
Also, tried using the userscript too, through TamperMonkey on Chrome and it doesn't run too.

**Comment by qsniyg** [comment]
I just tried on TamperMonkey with Chrome, and it works (the website also), so it might be a bit harder to track down this issue then unfortunately.

By the website not working, what exactly happens? Does it not do anything when you paste a URL? Does it show "No larger image found"? Or does the website itself fail to load?

I tried using the URL you linked in the other issue (https://pbs.twimg.com/media/DeYgzIRXUAAe8C1.jpg), and this is what it shows me:

![](https://i.imgur.com/nyJyJOL.png)

However, both the image you linked, and the image that it has given (with `?name=orig` appended to the end), are the same size (752x1080), and nothing can really be done about this, as this is the largest URL twitter can give us (in other words, this was the size of the image uploaded to twitter). The script only does URL redirection, it can't do reverse image search, [as it would be relatively unfeasible](https://www.reddit.com/r/RequestABot/comments/8gdmbi/a_bot_that_reverse_image_search_on_google_and/dyb5e3u/).

You said in the other issue that there was a larger image available, were you referring to a larger image available on the net? Or from the tweet itself?

If you meant the former, via reverse image search, I found a different tweet that had a much larger version of the image available. The linked image was:

https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg (835x1200)

And when using the userscript/website (or by adding `?name=orig` to the end), it results in:

https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg?name=orig (1782x2560)

But I don't believe the image from the tweet you linked (https://twitter.com/zerods_/status/1001524620523134981) has a larger version.

I'm not quite sure what the issue is, so I'm trying to attack it on the angles I can think of. If none of what I wrote above is applicable, please let me know the version of Chrome and Tampermonkey you have, and I'll try testing it under that configuration.

**Comment by bbtora** [comment]
> By the website not working, what exactly happens? Does it not do anything when you paste a URL?

This.

> that there was a larger image available, were you referring to a larger image available on the net? Or from the tweet itself?

I was referring from the tweet itself as was the case with "https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg"

> I found a different tweet that had a much larger version of the image available.

May I know how to find a twitter hosted image to its original tweet?

> But I don't believe the image from the tweet you linked (https://twitter.com/zerods_/status/1001524620523134981) has a larger version

But it does show a larger resolution image from the site result.

> please let me know the version of Chrome and Tampermonkey you have

Chrome version 67 and Tampermonkey 4.6

Today too, the site's not working on my browser and neither is the script.

**Comment by qsniyg** [comment]
>This.

Awesome, in which case, it's probably an issue I can fix, I'll try it under Chrome 67 and see if I can reproduce the issue.

>I was referring from the tweet itself as was the case with "https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg"

I see, this was from a different tweet though, which uploaded a larger image: https://twitter.com/HIGAN0M/status/1001061932001046529

>May I know how to find a twitter hosted image to its original tweet?

I just used google reverse image search, there were 2 tweets, one of which had the dimensions you linked (and the same URL), the other I linked above. I'm not sure if there's a proper method of doing so (I would doubt it, as media is uploaded before the tweet is created, then attached to the tweet when creating it)

>But it does show a larger resolution image from the site result

Could you show a screenshot of what you mean? We might be talking about the same thing here, but using different terms

**Comment by qsniyg** [comment]
Alright I just tried, I'm still unable to reproduce the issue. Could you go to the website, press F12 (to open up the developer tools), go to the console tab (at the top, beside "Elements" and "Sources"), and then paste https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg into it?

This is how it looks like on my machine:

![](https://i.imgur.com/69n2mCi.png)

**Comment by bbtora** [comment]
This is what I'm getting.

![chrome_2018-05-31_00-22-08](https://user-images.githubusercontent.com/23010526/40741273-c667b092-6468-11e8-90b0-ea98c8f92927.png)

**Comment by qsniyg** [comment]
Sorry, I meant, pasting the image URL in the textbox (saying `Paste image URL here`)

**Comment by bbtora** [comment]
There does seem to be an error.

![chrome_2018-05-31_00-27-19](https://user-images.githubusercontent.com/23010526/40741531-6cb14058-6469-11e8-9aba-5d1b5a752a47.png)

**Comment by qsniyg** [comment]
Interesting. I've (hopefully) fixed the crashing issue, but I don't think I've fixed the root cause of it yet, which means it'll very likely still not work.

I've just released a new update, can you try updating the script via greasyfork (https://greasyfork.org/en/scripts/36662-image-max-url), then opening a new tab, pressing F12 to open the developer console, and then trying going to these 2 URLs:

https://image.tmdb.org/t/p/w500/76gfJrmdBADyJJXqI0GRgj01yUo.jpg

https://img-pholar.pstatic.net/20161120_290/1479626135018LJPrw_JPEG/p?type=ffn720_720

And then the usual tweet:

https://pbs.twimg.com/media/DeR8RnBXkAAvKV2.jpg

If any of these don't work, could you attach a screenshot including the developer console?

(The reason for the first 2 URLs is because they're from the beginning and the end of the script, so there might be something along the way that breaks them)

The CDN the website uses is a bit behind, so the website is still using the old version of the code (you can test this via the tmdb URL, if it doesn't work, the website is still using the old version), so you'll have to test with the userscript instead.

**Comment by bbtora** [comment]
None of the following images work. Used updated script.

![chrome_2018-05-31_14-48-37](https://user-images.githubusercontent.com/23010526/40773946-f6ce99de-64e1-11e8-9b09-5813ef4ac403.png)
![chrome_2018-05-31_14-49-57](https://user-images.githubusercontent.com/23010526/40773947-f725d9a6-64e1-11e8-9003-b73474961b84.png)
![chrome_2018-05-31_14-50-20](https://user-images.githubusercontent.com/23010526/40773948-f77e0482-64e1-11e8-893a-bf04ef9737e5.png)

Site also still doesn't work

**Comment by qsniyg** [comment]
Alright, I googled the issue, and it turns out this script isn't the only one affected by this issue:

https://our.umbraco.org/forum/using-umbraco-and-getting-started/91715-js-error-when-aligning-content-left-center-right-justify-in-richtext-editor

It seems to be a bug in some versions of chrome. I just pushed a new update, using a pure javascript solution to work around the problem. Try updating the script and see if it works.

**Comment by bbtora** [comment]
Yep, the script's working now. 

The site is still not working although it does show invalid URL when I type something.
Here's the screencap with the error.
You can ignore the "googletagmanager" resource block as it was done by ublock origin.

![chrome_2018-05-31_17-12-42](https://user-images.githubusercontent.com/23010526/40780440-f30e339a-64f5-11e8-8ffb-247c7f519fa2.png)

**Comment by qsniyg** [comment]
Yeah, the github CDN is a bit slow to update, it'll be fine in a few hours (hopefully, anyways). Thank you for reporting this!
